pipeline {
    agent any

    tools {
        jdk 'MyJDK'   // must match Jenkins JDK configuration
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'chmod +x gradlew'
                sh './gradlew clean build'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Verify Build') {
            steps {
                sh 'ls -l build'
            }
        }
    }

    post {
        success {
            echo '✅ Gradle Build Successful!'
        }
        failure {
            echo '❌ Gradle Build Failed!'
        }
        always {
            echo '📌 Pipeline execution completed'
        }
    }
}
